### ISSUE TITLE
More control over users/devices

### ISSUE THREAD

**Issue by hooray4me** [freifunkMUC/wg-access-server#215]
Is it possible to add some controls on number of devices a user can register. It would be nice to have some of these controls in the admin portal, not just a MAX device variable or something in the config.yaml.

Any future plans to be able to set additional parameters per user, when a config is created? IE some users only have access to our streaming server, so their config is and allowed ips are fairly simple. But a few users may get access to the whole network... 

I like your build over https://github.com/ngoduykhanh/wireguard-ui , but some of the functionality in that one is wanted...

Thanks!

**Comment by DasSkelett** [comment]
> Is it possible to add some controls on number of devices a user can register. It would be nice to have some of these controls in the admin portal, not just a MAX device variable or something in the config.yaml.

We currently only use the config.yaml (and environment variables) for read-only configuration, we don't write any changes back to it or save any configuration in the database.
Thus I can see this happen as global setting that applies to all users, but I don't think we can make this editable and configurable per user in the UI (without more effort). Even more so because in the case of OIDC, we don't even know all users that could possibly login.

> Any future plans to be able to set additional parameters per user, when a config is created? IE some users only have access to our streaming server, so their config is and allowed ips are fairly simple. But a few users may get access to the whole network...

Similar to the above, and IMHO this is out of scope for wg-access-server, at least at the moment.
