### ISSUE TITLE
Original Author here

### ISSUE THREAD

**Issue by Place1** [freifunkMUC/wg-access-server#67]
Hey guys, just saw this fork on hackernews: https://news.ycombinator.com/item?id=30047440

Just wanted to say thanks and wish you the best for where you decide to take the code in the future :D

**Comment by GoliathLabs** [comment]
@Place1 thank you very much for your great work on this project. Without you it would not have been possible for us to work on it ourselves. Maybe there is a chance that our changes can be merged upstream?

**Comment by GoliathLabs** [comment]
@Place1 Since we have seen that there is still some interest in this project in the community, would it be possible for us to continue your legacy as maintainers for project? Most people are still using your repository, which does not yet include features such as IPv6, ARM support, etc.

Thus we'd like to ask if you'd be up for a repository transfer so that we can continue with the user base that your repository currently has and provide ongoing support for it? (https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository)

**Comment by GoliathLabs** [comment]
Or maybe link to this fork and archive the repo so new users can get the new features and updates of this fork instead
