### ISSUE TITLE
(request) Heruko deployment

### ISSUE THREAD

**Issue by mangopissemand1** [freifunkMUC/wg-access-server#73]
As the title says, make it useable for heruko so we can depoly there

**Comment by DasSkelett** [comment]
For someone completely unfamiliar with Heroku, how would that look like? What would need to be done to make the project usable with Heroku?
Would this only require action once (like creating some sort of config file in the repository, similar to docker-compose.yml or Helm charts), or would this require continuous maintenance?

**Comment by mangopissemand1** [comment]
My use case is to use their servers as they are hosted on aws for free. I dont know about all the other parts, but i've seen it done before, but not using wireguard

**Comment by DasSkelett** [comment]
Since we don't have any details and don't know how this "usable for Heroku" looks like, and since I'd have to spend a lot of time looking into Heroku and learning the ins and outs of it, figuring out how it works, what we'd have to do, and all for a questionable benefit, I'd consider this out of scope for the project.

If someone else give us more details in the future, we can pick it up again.
