### ISSUE TITLE
Add supported architectures

### ISSUE THREAD

**Issue by GoliathLabs** [freifunkMUC/wg-access-server#76]
All upstream images used support both ppc64le and s390x architectures. Therefore, I would like to add them to our Docker build as well (just in case someone using those architectures wants to use our image).

Regarding the extra time needed to build the images: The additional architectures are only built when commits are pushed to master, so it will only take a little more time after a PR is merged.

**Comment by DasSkelett** [comment]
"A little" is relative, the go binary compilation for the ARM images take ages (and for some reason don't seem to be re-used from cache as often):
- arm/v7:  [1884.3s](https://github.com/freifunkMUC/wg-access-server/runs/4923436460?check_suite_focus=true#step:7:1122) [2497.6s](https://github.com/freifunkMUC/wg-access-server/runs/4875586234?check_suite_focus=true#step:7:1435)
- arm64: [2069.4s](https://github.com/freifunkMUC/wg-access-server/runs/4923436460?check_suite_focus=true#step:7:1142) [2717.2s](https://github.com/freifunkMUC/wg-access-server/runs/4875586234?check_suite_focus=true#step:7:1481)
- amd64: [cached](https://github.com/freifunkMUC/wg-access-server/runs/4923436460?check_suite_focus=true#step:7:240) [376.6s](https://github.com/freifunkMUC/wg-access-server/runs/4875586234?check_suite_focus=true#step:7:1197)

We will inevitably run into race situations, where a PR merged after a previous one will finish first, and the previous one will overwrite the `latest` / `master` tag.

These QEMU userspace VMs that buildx uses are slow as hell.
I did [experiment](https://github.com/DasSkelett/wg-access-server/commit/6c0ac4490de6d454a189220fb1c9fbdd5c547225) with using Go's cross-compilation feature ([blog post](https://github.com/DasSkelett/wg-access-server/blob/fix/docker-cross-compile/cross-compile.md), [my notes](https://github.com/DasSkelett/wg-access-server/blob/fix/docker-cross-compile/cross-compile.md)) while running the build stages on the native architectures, but since we depend on CGO (the PostgreSQL driver links with/includes C code) we also need a C cross-compilation toolchain, which Alpine doesn't package.
One can [download](https://github.com/DasSkelett/wg-access-server/blob/6c0ac4490de6d454a189220fb1c9fbdd5c547225/Dockerfile#L35-L38) pre-built ones from various websites, but this isn't really something I want to do for a production image.

**Comment by DasSkelett** [comment]
Well, we already haven encountered such a situation right now:
![Docker image build race condition](https://user-images.githubusercontent.com/28812678/151072449-f50ab1da-7f28-4aa6-b45c-35c7e1d6cb01.png)

Fortunately the changes there are not end-user visible, but it's definitely a problem.

**Comment by GoliathLabs** [comment]
Yeah, you're right. We might just build for those additional architectures when a new tag is created then?

**Comment by DasSkelett** [comment]
Would be a possible solution, but that leaves the risk of an architecture breaking without anyone noticing until a release happens. Unlikely to happen (for our code at least, it's all true, platform-independent Go code), though.

Alternatively, we could switch the base images to e.g. Debian, where all the cross-compilation toolchains are packaged. But that would bump the image size quite a bit.
Or maybe we split them, basing the amd64 image on Alpine and all other ones on Debian? But that would mean two Dockerfiles need to be maintained, and possible confusion on the user side.

I can't really see a nice and easy solution yet.

**Comment by DasSkelett** [comment]
Apparently the number of jobs running in parallel is unlimited by default for buildx and the build-push-action.
With the CPU- and RAM-heavy compilation on the relatively low-powered GitHub Actions VMs, all the context switches might be slowing it down quite a bit.
There is an easy way to limit the parallelism: https://github.com/docker/setup-buildx-action#max-parallelism

I'm going to try out and see if setting this to a lower value speeds the build up.
